[versions]
agp = "9.2.0"
ndk = "27.0.12077973"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activityKtx = "1.8.0"
constraintlayout = "2.1.4"
arcore = "1.45.0"
litert = "2.1.4"
litertGpu = "1.4.2"
litertlm = "0.10.2"
qnnDelegate = "2.44.0"
coroutines = "1.7.3"
djl = "0.33.0"
lifecycleRuntimeKtx = "2.8.7"

[libraries]
arcore = { group = "com.google.ar", name = "core", version.ref = "arcore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
litert-core = { group = "com.google.ai.edge.litert", name = "litert", version.ref = "litert" }
litert-gpu = { group = "com.google.ai.edge.litert", name = "litert-gpu", version.ref = "litertGpu" }
litert-qnn = { group = "com.qualcomm.qti", name = "qnn-litert-delegate", version.ref = "qnnDelegate" }
litertlm-android = { group = "com.google.ai.edge.litertlm", name = "litertlm-android", version.ref = "litertlm" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
djl-api = { group = "ai.djl", name = "api", version.ref = "djl" }
djl-android-core = { group = "ai.djl.android", name = "core", version.ref = "djl" }
djl-android-tokenizer-native = { group = "ai.djl.android", name = "tokenizer-native", version.ref = "djl" }
djl-sentencepiece = { group = "ai.djl.sentencepiece", name = "sentencepiece", version.ref = "djl" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

