#!/usr/bin/env bash
# Populate model assets for Callback.
# Run from the repo root.  Models are gitignored — re-run on a fresh clone.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${ROOT}/app/src/main/assets"
mkdir -p "${DEST}"

echo "=== Callback model setup ==="
echo ""
echo "── BUNDLED MODELS (go into app/src/main/assets/) ──────────────────────"
echo ""
echo "1. detector_yolov8.tflite  (12 MB)"
echo "   Source: Qualcomm AI Hub — job j5wm6ok4g (YOLOv8n float SM8750)"
echo "   Already present if you ran the benchmark. Otherwise download from AI Hub"
echo "   and place at: ${DEST}/detector_yolov8.tflite"
echo ""
echo "2. embedding-gemma.tflite  (186 MB)"
echo "   Source: litert-community/EmbeddingGemma-300M on Hugging Face"
echo "   Prerequisites: huggingface-cli login (accept EmbeddingGemma license gate)"
echo ""
echo "   huggingface-cli download litert-community/EmbeddingGemma-300M \\"
echo "       --include '*.tflite' --include 'sentencepiece.model' \\"
echo "       --local-dir \"${DEST}\""
echo "   # Rename if needed:"
echo "   # mv \"${DEST}/embeddinggemma-300m.tflite\" \"${DEST}/embedding-gemma.tflite\""
echo "   # sentencepiece.model (~4.6 MB) must stay named sentencepiece.model for DJL tokenization."
echo ""
echo "── DEVICE-SIDE MODEL (NOT bundled in APK — 2.8 GB) ────────────────────"
echo ""
echo "3. gemma-4-E2B-it_qualcomm_sm8750.litertlm  (2.8 GB)"
echo "   Source: litert-community/gemma-4-E2B-it-litert-lm on Hugging Face"
echo "   Prerequisites: huggingface-cli login (accept Gemma license gate)"
echo ""
echo "   # Download to a scratch dir (do NOT put in app/src/main/assets):"
echo "   huggingface-cli download litert-community/gemma-4-E2B-it-litert-lm \\"
echo "       --local-dir /tmp/gemma4"
echo ""
echo "   # Push to device (app must be installed first so the dir exists):"
echo "   adb push /tmp/gemma4/gemma-4-E2B-it_qualcomm_sm8750.litertlm \\"
echo "       /sdcard/Android/data/com.bhuvan.callback/files/gemma-4-E2B-it_qualcomm_sm8750.litertlm"
echo ""
echo "   # Verify:"
echo "   adb shell ls -lh /sdcard/Android/data/com.bhuvan.callback/files/"
echo ""
echo "── AFTER SETUP ─────────────────────────────────────────────────────────"
echo ""
echo "   ls -lh ${DEST}/"
echo "   # Expected:"
echo "   #   detector_yolov8.tflite   ~12 MB"
echo "   #   embedding-gemma.tflite  ~186 MB"
echo "   #   yolov8_labels.txt         <1 KB"
echo ""
echo "   Build + install: ./gradlew assembleDebug && ./gradlew installDebug"
echo "   Then adb-push Gemma if not already on device (see step 3 above)."
echo ""
echo "See SPEC.md §4 for full model specs and §9 for the permissions rationale."
